# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-local-pv
  namespace: logging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  local:
    path: /mnt/data/elasticsearch  # Ensure this path exists on your MicroK8s node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "fried-potato"  # Replace with your node name, if needed

