apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 5Gi
