# elasticsearch.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      namespace: logging
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
        env:
        - name: discovery.type
          value: "single-node"
        volumeMounts:
        - name: elasticsearch-local-pvc
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            memory: "1Gi"
  
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: elasticsearch-local-pvc
      namespace: logging
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi


