# kibana.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      namespace: logging
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.15.3
        ports:
          - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
          value: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuX0lUREIySklCQXpCUDh3Yk9XX1BJOlRPbFYzaUF5UmRtdXFmVmNhcjRfdnc
        resources:
          limits:
            memory: "1Gi"

