apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: logging
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30001  # Change as desired
