apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: logging
data:
  ds.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy 
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: true
      version: 1
      editable: false

