# loki.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: logging
spec:
  selector:
    matchLabels:
      app: loki
  serviceName: "loki"
  replicas: 1
  template:
    metadata:
      namespace: logging
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        args:
          - '-config.file=/etc/loki/loki-config.yaml'
        ports:
          - containerPort: 9200
          - containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"
        volumeMounts:
        - name: loki-local-pvc
          mountPath: /var/lib/loki
        - name: loki-config
          mountPath: /etc/loki
        resources:
          limits:
            memory: "1Gi"
      volumes:
        - name: loki-config
          configMap:
            name: loki-config

  
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: loki-local-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi


